name = "NeuralCollaborativeFiltering"
uuid = "4926af98-24ac-477d-9236-1ef7e29a8999"
authors = ["Mikhail Poludin"]
version = "1.0.0-DEV"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1.9"
